const assert = require('node:assert/strict');
const {execFileSync} = require('node:child_process');
const path = require('node:path');
const cli = process.env.AGENT_BROWSER || 'agent-browser';
const session = 'gt-consistent-verify';
const design = process.env.GT_DESIGN === 'refined' ? 'refined' : 'current';
const url = `http://127.0.0.1:8769/.scratch/consistent-learning-table/prototype/?design=${design}`;
const evidence = path.resolve(__dirname,'../evidence');
const call = (...args) => {
  const result = JSON.parse(execFileSync(cli,['--session',session,'--json',...args],{encoding:'utf8',timeout:30000}));
  assert.equal(result.success,true,JSON.stringify(result.error));
  return result.data;
};
const evalJs = code => call('eval',code).result;
const click = (action,value) => call('click',`[data-action="${action}"]${value===undefined?'':`[data-value="${value}"]`}`);
const shot = name => call('screenshot','body',path.join(evidence,design==='refined'?`refined-${name}`:name));
const box = () => evalJs('(() => { const r=document.querySelector(".table-wrap").getBoundingClientRect(); return {x:r.x,y:r.y,w:r.width,h:r.height} })()');
const noOverflow = () => assert.equal(evalJs('document.documentElement.scrollWidth <= innerWidth'),true);
const enter = mode => {click('exit');click('open',mode);if(evalJs('state.stage')==='intro')click('start')};
const checks=[];
const pass=name=>{checks.push(name);console.log('PASS '+name)};

call('open',url);call('set','viewport','375','812');
assert.equal(evalJs('state.stage'),'intro');
assert.equal(evalJs('document.querySelectorAll(".intro-visual .seat").length'),4);
assert.ok(evalJs('document.querySelector(".intro-visual").textContent.includes("11칩")'));
shot('pot-intro-ko-light.png');
click('start');
assert.equal(evalJs('state.stage'),'practice');
assert.equal(evalJs('document.querySelector(".pot-center").getAttribute("aria-label").includes("43")'),false);
assert.equal(evalJs('document.querySelector(".table").textContent.includes("43")'),false);
assert.equal(evalJs('document.querySelectorAll(".choice").length'),3);
assert.equal(evalJs('document.querySelector("[data-action=help]").disabled'),true);
const initial=box();
click('next');click('back');assert.equal(evalJs('state.step'),0);
for(let i=0;i<6;i++)click('next');
assert.equal(evalJs('state.step'),6);
assert.deepEqual(box(),initial);
assert.equal(evalJs('document.querySelector(".active-action").textContent.includes("18칩")'),true);
assert.equal(evalJs('document.querySelector(".active-action").textContent.includes("12칩")'),false);
click('back');assert.equal(evalJs('document.querySelector(".active-action").textContent.includes("16칩")'),false);click('next');
assert.equal(evalJs('document.querySelector(".pot-center").getAttribute("aria-label").includes("43")'),false);
const choiceStyle = evalJs('[...document.querySelectorAll(".choice")].map(x=>[getComputedStyle(x).backgroundColor,getComputedStyle(x).borderColor])');
assert.deepEqual(choiceStyle[0],choiceStyle[1]);assert.deepEqual(choiceStyle[1],choiceStyle[2]);
shot('pot-final-hidden-ko-light.png');
click('replay');assert.equal(evalJs('state.step'),0);
for(let i=0;i<6;i++)click('next');
click('answer','45');assert.equal(evalJs('document.querySelector(".result").dataset.result'),'incorrect');
assert.deepEqual(box(),initial);click('steps');assert.ok(evalJs('document.querySelector(".steps").textContent.includes("1 + 2 + 6 + 6 + 16 + 12 = 43")'));
shot('pot-incorrect-steps-ko-light.png');
pass('Pot replay/back, fixed table bounds, hidden visual and accessibility total, equal choices, incorrect steps');

click('exit');click('open','pot');assert.equal(evalJs('document.querySelector(".result").dataset.result'),'incorrect');
click('intro');assert.equal(evalJs('state.stage'),'intro');click('skip');assert.equal(evalJs('document.querySelector(".result").dataset.result'),'incorrect');
pass('Exit/resume and intro reopen preserve practice state');
evalJs('state.answered=null;state.assisted=false;state.showSteps=false;state.step=6;render()');
click('help');assert.equal(evalJs('document.querySelector("[data-help=true]").textContent.includes("BB 18")'),true);
assert.equal(evalJs('document.querySelectorAll(".choice:not(:disabled)").length'),3);
click('answer','43');assert.equal(evalJs('document.querySelector(".result").dataset.result'),'assisted');shot('pot-assisted-ko-light.png');
evalJs('state.answered=null;state.assisted=false;state.showSteps=false;state.step=6;render()');
click('answer','43');assert.equal(evalJs('document.querySelector(".result").dataset.result'),'correct');shot('pot-correct-ko-light.png');
pass('Assisted choice remains selectable and credited as helped; unaided correct uses same table bounds');

enter('position');
assert.deepEqual([box().w,box().h],[initial.w,initial.h]);
assert.equal(evalJs('document.querySelectorAll(".seat.active").length'),0);
assert.equal(evalJs('document.querySelector(".table").textContent.includes("마지막")'),false);
click('answer','button');assert.equal(evalJs('document.querySelector(".result").dataset.result'),'correct');
click('intro');click('example');assert.ok(evalJs('document.querySelector(".intro-visual").textContent.includes("공용 카드 전")'));
shot('position-example-ko-light.png');
pass('Position question conceals answer; intro compares preflop and postflop order');

enter('combos');click('intro');click('example');assert.equal(evalJs('document.querySelectorAll(".example-pairs span").length'),6);
assert.equal(evalJs('new Set([...document.querySelectorAll(".example-pairs span")].map(x=>x.textContent)).size'),6);
shot('combos-example-ko-light.png');click('start');click('answer','12');assert.equal(evalJs('document.querySelector(".result").dataset.result'),'correct');
pass('Combos first-use six distinct AA pairs and AKo question');

enter('play');for(let i=0;i<2;i++)click('next');
assert.deepEqual([box().w,box().h],[initial.w,initial.h]);
assert.equal(evalJs('document.querySelectorAll(".seat.folded .card.back").length'),2);
assert.equal(evalJs('document.querySelectorAll(".seat .card:not(.back)").length'),2);
click('next');click('next');assert.equal(evalJs('document.querySelectorAll(".board .card").length'),3);
assert.equal(evalJs('(() => {const b=document.querySelector(".board").getBoundingClientRect(),others=[...document.querySelectorAll(".seat,.pot-center")].map(x=>x.getBoundingClientRect());return others.some(r=>b.left<r.right&&b.right>r.left&&b.top<r.bottom&&b.bottom>r.top)})()'),false);
assert.equal(call('a11y','--tags','wcag2a,wcag2aa').counts.violations,0);
shot('play-fold-board-ko-light.png');
pass('Play shares table/card rendering; folded opponent cards stay face down and board appears');

call('select','#language','en');call('select','#theme','dark');call('select','#text-size','large');
assert.equal(evalJs('state.lang'),'en');assert.equal(evalJs('state.theme'),'dark');assert.equal(evalJs('state.size'),'large');
noOverflow();shot('play-en-dark-large.png');
enter('pot');evalJs('state.answered=null;state.assisted=false;state.showSteps=false;state.step=6;render()');noOverflow();shot('pot-final-en-dark-large.png');
assert.equal(box().h,280);
const reachable=evalJs('(() => {const a=document.querySelector(".app"),b=document.querySelector(".choice");a.scrollTop=a.scrollHeight;const r=b.getBoundingClientRect(),v=a.getBoundingClientRect();return r.bottom<=v.bottom&&r.top>=v.top})()');
assert.equal(reachable,true);
assert.equal(call('a11y','--tags','wcag2a,wcag2aa').counts.violations,0);
call('set','media','dark','reduced-motion');
assert.equal(evalJs('matchMedia("(prefers-reduced-motion: reduce)").matches'),true);
assert.ok(evalJs('parseFloat(getComputedStyle(document.querySelector(".button")).transitionDuration)')<0.01);
pass('English, dark, large text, scroll reachability and reduced motion');

call('press','Tab');
assert.ok(evalJs('document.activeElement && document.activeElement.tagName!=="BODY"'));
assert.equal(evalJs('getComputedStyle(document.activeElement).outlineStyle')==='none',false);
call('press','Escape');assert.equal(evalJs('state.stage'),'home');
noOverflow();
pass('Keyboard focus and Escape exit');
console.log(`${checks.length} groups passed`);
